# # схема обработки исключений:
# #
# # try :
# #     checkCode()
# # except :
# #     handleError()
# # finally :
# #     finishChecking()
# #
# # print(int('ert'))
# # print(2 + эвап)
#
# try :
#     print(2 + 'эвп')
# except :
#     print('error!')
# finally :
#     print('Проверка завершена.')

# word = 'python'
# print(word[-7])
anme = "er3w4f"
print(('you\'re'))